name: Lint and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.13
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.4.1
      with:
        version: 2.0.1
        virtualenvs-create: true
        virtualenvs-in-project: false
        installer-parallel: true

    - name: Install project dependencies
      run: poetry install -E dev

    - name: Run pre-commit
      run: poetry run pre-commit run --all-files

    - name: Run tests
      run: poetry run pytest . --junitxml=pytest.xml | tee pytest-coverage.txt

    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@v1.1.53
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
