name: Pulumi-Destroy
on:
  - workflow_dispatch
jobs:
  pulumi-destroy:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.3.0
        with:
            python-version: 3.13
      - run: pip install -r deployment/requirements.txt
      - name: gcloud login
        run: |
          echo $GOOGLE_CREDENTIALS > google_key.json
          gcloud auth activate-service-account --key-file=google_key.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      - name: docker login
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - uses: pulumi/actions@v6.0.1
        with:
          command: destroy
          stack-name: dev
          work-dir: deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
