name: Pulumi-Preview
on:
  workflow_dispatch:
  pull_request:
      branches: [ master ]
jobs:
  pulumi-preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5.0.0
        with:
            python-version: 3.12
      - run: pip install -r deployment/requirements.txt
      - name: gcloud login
        run: |
          echo $GOOGLE_CREDENTIALS > google_key.json
          gcloud auth activate-service-account --key-file=google_key.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      - name: docker login
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - uses: pulumi/actions@v5.1.1
        with:
          command: preview
          stack-name: dev
          work-dir: deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
